### ISSUE TITLE
Error with loading library

### ISSUE THREAD

**Issue by SmimOfficial** [Climeron/PvZ-Fusion-BlackScreenFix#2]
I put the .dll files in the mods folder in my PvZ, also unpacked the archives there, and when starting the game writes: Failed to initialize MelonLoader: Failed to load library! How to solve this problem?

**Comment by Climeron** [comment]
As I understand it, you only had the game installed. Write down point by point what you did to get this error. Specify what you downloaded, where you downloaded it from and where you installed it. Specify which version of MelonLoader you are trying to install. And also check if all the required [libraries](https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements) are installed.

**Comment by SmimOfficial** [comment]
Ok

**Comment by SmimOfficial** [comment]
Oh, I forgot download libraries

**Comment by SmimOfficial** [comment]
Ok, I downloaded all .net programms, but MelonLoader still not working

**Comment by SmimOfficial** [comment]
And if I'm in Russia, can it affect the work of MelonLoader? (discord is currently blocked in Russia due to small details that the government could not remove itself)

**Comment by SmimOfficial** [comment]
i loaded 0.6.6 to game
also i see in the corner of the MelonLoader "v4.0.1"

**Comment by SmimOfficial** [comment]
Is it supposed to look like this? 
![Screenshot](https://github.com/user-attachments/assets/8cfabaf1-ebfc-40cc-9e9d-69bc9126372a)
(The folder Mods is located in the folder with the game)

**Comment by Climeron** [comment]
Тьфу ты, так если ты из России, чё тогда на английском пишешь? 😄
MelonLoader не имеет никаких ограничений. Это простой загрузчик модов. В папке Mods, как написано в инструкции, должны находиться только dll файлы, как у тебя на скрине. То, что ты скачал дополнительно (архив Source code), тебе не нужно.
Если ты MelonLoader установил корректно, и установлены все библиотеки для него, то должно работать.
Если есть какие-то ещё проблемы, где-то в папке MelonLoader или его подпапках есть файл Latest.log. Скинь его сюда.

**Comment by SmimOfficial** [comment]
Логично, ведь создатель должен быть не из страны с английским языком.

Я скачивал MelonLoader с официального репозитория в гитхаб, выбрал .exe файл игры, установил туда 0.6.6.

Когда руки дойдут до компьютера, я проверю лог

**Comment by SmimOfficial** [comment]
[Latest-Bootstrap.log](https://github.com/user-attachments/files/17870129/Latest-Bootstrap.log)

**Comment by SmimOfficial** [comment]
Ема я тупой, я скачал MelonLoader.Installer

**Comment by SmimOfficial** [comment]
пойду спрошу [здесь](https://github.com/LavaGang/MelonLoader.Installer)

**Comment by Climeron** [comment]
У тебя получилось решить проблему?

**Comment by Anzarot121** [comment]
У меня такая же проблема была. MelonLoader ненавидит всё что не латиница, нужно переименовать папку с игрой.

**Comment by SmimOfficial** [comment]
> У меня такая же проблема была. MelonLoader ненавидит всё что не латиница, нужно переименовать папку с игрой.

я переименовал папку с игрой с русского на латиницу, теперь все работает
