### ISSUE TITLE
Прикол с модом

### ISSUE THREAD

**Issue by SegMate** [Climeron/PvZ-Fusion-BlackScreenFix#3]
Здравствуйте, мод установился нормально, игра запустилась, но в любом уровне игры солнце не тратится, а растения не имеют кд и ставится в одну клетку на поле до бесконечности

**Comment by SegMate** [comment]
Версия игры-2.1.5

**Comment by Climeron** [comment]
Удостоверьтесь, что вы установили корректные версии BlackScreenFix и ClimeronToolsForPvZ. Либо вы не установили тулзы, либо фикс, предназначенный для версии 2.1.4.
